### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by phemmylintry** [obidient/23ForObiApi#6]
## Endpoints
Endpoints are provided by [bigfastapi](https://bigfa.st/docs/socialauth)

## Example
```python
from bigfastapi.auth import app as auth
 
app.include_router(auth, tags=[Auth])
```

**Comment by blacdev** [comment]
@phemmylintry I would like to start with this task. Do I need to do anything?

**Comment by phemmylintry** [comment]
@blacdev Just clone the project and implement it. Then PR when done. Thanks

**Comment by blacdev** [comment]
Okay
